language: java
sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386
install: #ignore tests
  - true
script:
  - mvn clean install -DskipTests
jdk:
  - oraclejdk8
