language: java
sudo: true
before_script:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386
install:
  - true
script:
  - mvn clean install -DskipTests
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
